### PR TITLE
about page

### PR DESCRIPTION
**Pull request by tejus0**
Please Provide The following Details About your PR

Type x Inside the checkbox to tick it

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by tejus0** [comment]
this is about section

**Comment by pdcode1** [comment]
Hi, we follow a css pattern, you need
change css file name, "about.css" to "about.styles.css"
so, you don't needed writting full html, just use django to extends base.html
like: "select_choices.html"...
Please, fix those things  to be approved!

@tejus0

**Comment by cassreinhart** [comment]
Hi, Pedro! I updated the templates and everything should be good to go. The styling is affecting the other pages, so I commented out the link tag until we can figure that out, but the page works!

**Comment by cassreinhart** [comment]
Let me know if everything looks good please!

**Comment by pdcode1** [comment]
Hi, I reviewed this P.R it's okay! Thanks for contributing!

**Comment by pdcode1** [comment]
@kailashchoudhary11

**Review by kailashchoudhary11 — APPROVED** [review]

**Pull request merged**
