### PR TITLE
Edited Readme.md file

### PR DESCRIPTION
**Pull request by pratyusha0710**

### CODE REVIEW

**Comment by kailashchoudhary11** [comment]
Don't make these changes! Just remove the running locally part and its subsections from the table of content

**Comment by pratyusha0710** [comment]
Ok

**Comment by kailashchoudhary11** [comment]
@pratyusha0710  Also let me know if you would like to contribute to frontend!

**Comment by pratyusha0710** [comment]
I made the required changes.

**Comment by pratyusha0710** [comment]
@kailashchoudhary11 would frontend require coding? I am just doing non-code issues right now

**Review by kailashchoudhary11 — APPROVED** [review]
Thanks for contributing :) I am merging the PR don't forget to Give a Star to the repository!

**Pull request merged**
