### PR TITLE
New efficient Encrption and Decryption algorithm for image added

### PR DESCRIPTION
**Pull request by bhoopesh369**
Please Provide The following Details About your PR

Type x Inside the checkbox to tick it

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by bhoopesh369** [comment]
Heyy I have added crypto encryption and decryption algorithms for images

**Comment by bhoopesh369** [comment]
You can now merge this PR @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
@bhoopesh369 Update requirements.txt file as well

**Comment by kailashchoudhary11** [comment]
@bhoopesh369 Also I'm getting some errors while executing those functions. Default key 123 seems to be incorrect

**Comment by bhoopesh369** [comment]
Heyy actually the Pycrypto module is outdated it seems 
The latest version was released on 2013

**Comment by bhoopesh369** [comment]
I'll search for other algorithms @kailashchoudhary11

**Comment by bhoopesh369** [comment]
You can merge this PR if you want

**Comment by kailashchoudhary11** [comment]
> You can merge this PR if you want

Bro?

**Pull request closed without merging**
