### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #5: Add CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by hari-ajidesh**
Closes #5

### CODE REVIEW

**Comment by kailashchoudhary11** [comment]
Hey @hari-ajidesh Thank you for your contribution! May you please move the installation commands from the readme file to this file and provide the link of contributing file in the readme?

**Comment by hari-ajidesh** [comment]
Please add the hacktoberfest-accepted label to this issue

**Comment by hari-ajidesh** [comment]
Please look into this PR also

**Review by kailashchoudhary11 — APPROVED** [review]

**Comment by kailashchoudhary11** [comment]
I have merged this one! Don't forget to give a star to the repo!

**Pull request merged**
