### PR TITLE
Add Issue templates

### LINKED ISSUE #49: Create Template for Issues
Create template for Bug Report, New Feature Request, Improvement to Existing Functionality

### PR DESCRIPTION
**Pull request by israelmitolu**
Please Provide The following Details About your PR

Type x Inside the checkbox to tick it

## Description

I have added the issue templates for bug report, improvement to existing functionality and new feature request.

Fixes #49 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by kailashchoudhary11 — APPROVED** [review]

**Comment by kailashchoudhary11** [comment]
Thank you for contributing :) Dont' forget to give a star to the repository!!!

**Comment by israelmitolu** [comment]
Will do!

**Comment by kailashchoudhary11** [comment]
> Will do!

Would you like to contribute more?

**Comment by israelmitolu** [comment]
Yeah, sure. I'd love to

**Comment by kailashchoudhary11** [comment]
@israelmitolu You can join our discord server link is in the readme

**Pull request merged**
